// Bundled Japanese audio playback (spec Tier-0 "pre-bundled audio", fully
// offline). Clips are generated by tools/generate_audio.py (edge-tts) into
// assets/audio/ with a manifest (key → path). Play by lesson-item id or
// kana key (e.g. 'kana_hira_a'); missing clips are a silent no-op.
import 'dart:convert';

import 'package:flutter/services.dart' show rootBundle;
import 'package:just_audio/just_audio.dart';

class AudioService {
  AudioService._();
  static final AudioService instance = AudioService._();

  final AudioPlayer _player = AudioPlayer();
  Map<String, String>? _manifest;

  Future<Map<String, String>> _load() async {
    if (_manifest != null) return _manifest!;
    try {
      final raw = await rootBundle.loadString('assets/audio/manifest.json');
      _manifest = (json.decode(raw) as Map).cast<String, String>();
    } catch (_) {
      _manifest = const {};
    }
    return _manifest!;
  }

  /// True if a clip exists for this key (drives whether the 🔊 button shows).
  Future<bool> has(String key) async => (await _load()).containsKey(key);

  /// Play the clip for [key]. No-op (never throws) if absent or unplayable
  /// (e.g. web without the asset). Restarts if already playing.
  Future<void> play(String key) async {
    final m = await _load();
    final path = m[key];
    if (path == null) return;
    try {
      await _player.setAsset('assets/$path');
      await _player.seek(Duration.zero);
      await _player.play();
    } catch (_) {/* audio backend unavailable — stay silent */}
  }
}
