// Bundled Japanese audio playback (spec Tier-0 "pre-bundled audio", fully
// offline). Clips are generated by tools/generate_audio.py (edge-tts) into
// assets/audio/ with a manifest (key → path). Play by lesson-item id or
// kana key (e.g. 'kana_hira_a'); missing clips are a silent no-op.
import 'dart:convert';

import 'package:flutter/services.dart' show rootBundle;
import 'package:just_audio/just_audio.dart';

class AudioService {
  AudioService._();
  static final AudioService instance = AudioService._();

  AudioPlayer? _player;
  Map<String, String>? _manifest;

  Future<Map<String, String>> _load() async {
    if (_manifest != null) return _manifest!;
    try {
      final raw = await rootBundle.loadString('assets/audio/manifest.json');
      _manifest = (json.decode(raw) as Map).cast<String, String>();
    } catch (_) {
      _manifest = const {};
    }
    return _manifest!;
  }

  /// True if a clip exists for this key (drives whether the 🔊 button shows).
  Future<bool> has(String key) async => (await _load()).containsKey(key);

  /// Play the clip for [key]. No-op (never throws) if absent or unplayable
  /// (e.g. web without the asset).
  ///
  /// A FRESH player per call, disposing the previous one: reusing a single
  /// just_audio player with rapid setAsset is unreliable on web — it keeps
  /// replaying the FIRST-loaded clip instead of switching. A new player's
  /// element only ever holds one source, so the right clip always plays.
  /// Clips are <1s, so the create/dispose cost is negligible.
  Future<void> play(String key) async {
    final m = await _load();
    final path = m[key];
    if (path == null) return;
    final old = _player;
    final p = AudioPlayer();
    _player = p;
    try {
      if (old != null) {
        await old.stop();
        await old.dispose();
      }
      await p.setAsset('assets/$path');
      p.play(); // fire-and-forget; the future completes when the clip ends
    } catch (_) {/* audio backend unavailable — stay silent */}
  }
}
